### ISSUE TITLE
standalone.yml step 34 seems to have a incorrect path for the copy

### ISSUE THREAD

**Issue by peulvast** [ODMDev/odm-ondocker#127]
When I follow the steps described in dev, the step 34/51 fails on the copy because the ./teamserver is used instead of ../teamserver.

**Comment by yiquanzhou** [comment]
@peulvast I didn't reproduce the issue. What's the error that you got? Did you run ```docker-compose -f odm-standalone.yml build``` from /odm-ondocker? Thanks!

**Comment by peulvast** [comment]
I cannot reproduce anymore ...
I close the defect.
