### ISSUE TITLE
How to report issues ?

### ISSUE THREAD

**Issue by FrancoisTrible** [ODMDev/odm-ondocker#138]
I wanted to use  https://hub.docker.com/r/ibmcom/odm/

I'm not sure if I need to enter issues here, use the https://developer.ibm.com/answers/topics/ibmodm.html forum or send a mail to odmdev_open_source_user@wwpdl.vnet.ibm.com , as the contributing guidelines here say.

**Comment by lgrateau** [comment]
The both channel are valid. You can also:
  1/ enter issue in this github 
  2/ Interact on slack . Link is in the main README of this github.
