### ISSUE TITLE
Add support for JDBC to DB's running outside ICP (e.g. DB2, Oracle)

### ISSUE THREAD

**Issue by robomeister** [ODMDev/odm-ondocker#144]
For customers not wishing to deploy to a containerized database manager, it would be nice if there was an option to deploy the ODM components, pointing to either a DB2 or Oracle running elsewhere.

**Comment by lindsae** [comment]
@robomeister were you able to figure this out on your own?  I am trying to get this setup now and would appreciate any pointers on how you got it working.

**Comment by cconnar** [comment]
@lindsae This describes the topology for the ODM Standard Docker image, which has to be built manually using Docker Compose.  The steps to complete this are [outlined here](https://github.com/ODMDev/odm-ondocker/blob/master/docs/README_standard.md).

I personally ran into numerous script issues building this image in Windows and it should be easier to build in a POSIX system.

**Comment by lgrateau** [comment]
I confirm Windows is a little bit tricky due to the docker windows support. A better way on windows is to use a VM with Ubuntu.
