### ISSUE TITLE
odm-standalone_1  | [WARNING ] SRVE0190E: File not found: /favicon.ico

### ISSUE THREAD

**Issue by rachel-orti** [ODMDev/odm-ondocker#148]
On standalone, we have a warning "File not found: /favicon.ico".
We should find out where this warning comes from and fix it.

**Comment by Jeremy-Pichon** [comment]
- This problem looks to appear only on Firefox browser when you go to previous page.
- e.g : You are on Dashboard, you click on res link, then you go back to Dashboard. The error spawn here
- (Tested on Safari, Chrome, Firefox)
