### ISSUE TITLE
Stable branch for ODM 8.9.2

### ISSUE THREAD

**Issue by jphillips-bp3** [ODMDev/odm-ondocker#177]
Is there a stable branch that works against ODM 8.9.2, considering ODM 8.10 is not even released yet?

Or are there instructions on how to modify the Docker build files to work with ODM 8.9.2 instead?

**Comment by lgrateau** [comment]
Hi,

The master branch is stable and support the 8.10 and 8.9.2 releasew. We have automatic tests running in this 2  branches.

I hope this clarify the process. Maybe we will rename the default tag to master to be more clear.

**Comment by lgrateau** [comment]
If you want a the branch that we freeze during the 8.9.2.A you can use this release https://github.com/ODMDev/odm-ondocker/releases/tag/8.9.2.0_1.0.0 that you can use.

**Comment by jphillips-bp3** [comment]
> If you want a the branch that we freeze during the 8.9.2.A you can use this release https://github.com/ODMDev/odm-ondocker/releases/tag/8.9.2.0_1.0.0 that you can use.

Thank you, this is exactly what I was looking for.
