### ISSUE TITLE
DC and RES databases mounted outside the ODM for Developers Docker image are not read

### ISSUE THREAD

**Issue by FrancisFriedlander** [ODMDev/odm-ondocker#190]
I am using the Official IBM Operational Decision Manager for Developers image version 8.10.
If you first run the docker command line, option "-v $PWD:/config/dbdata/", this creates the resdb and rtsdb files in the current directory as expected. However, if you kill the container and run the command line again, the work done in the previous session (projects synchronized to DC, ruleapps deployed to RES) does not show.

**Comment by lgrateau** [comment]
Hi Francis ,
The 2nd time you need to set the parameter SAMPLE=false.

**Comment by FrancisFriedlander** [comment]
Thanks Laurent,
Indeed this solves the issue.
This means that if I am running with both the "-v $PWD:/config/dbdata/" and the "SAMPLE=true", this will overwrite what ever resdb.* and rtsdb.* files.
Many thanks,
Francis
