### ISSUE TITLE
Simulation freezes from time to time

### ISSUE THREAD

**Issue by FrancisFriedlander** [ODMDev/odm-ondocker#191]
I am using the Official IBM Operational Decision Manager for Developers image version 8.10. Simulation is freezing from time to time.

**Comment by lgrateau** [comment]
In your docker setting could you increase your memory
In Mac : Docker->Preference->Advanced Put 4Gb

**Comment by FrancisFriedlander** [comment]
Hi Laurent, I did it and it works fine. By the way I am using the very same options as for version 8.9.2.1: docker run -e LICENSE=accept -p 9060:9060 -p 9443:9443 -v $PWD:/config/dbdata/ -e SAMPLE=false ibmcom/odm:8.10

Thanks again,

Francis
