### ISSUE TITLE
Latest version supported for ODM is out of date

### ISSUE THREAD

**Issue by rachel-orti** [ODMDev/odm-ondocker#192]
In the docs folder, we have the following information:
Cluster: It applies to Operational Decision Management Standard V8.9.0.1 and to earlier versions up to v8.8.x.

Standalone: It applies to Operational Decision Manager Standard V8.9.0.x and to earlier versions up to V8.8.x.

Standard: It applies to Operational Decision Manager Standard V8.9.0.1 and to earlier versions up to v8.8.x.

The latest supported version for ODM must be updated and it must be the same for all the configurations.

**Comment by rachel-orti** [comment]
**Note that currently the supported versions for ODM are only listed on the dedicated pages for Cluster, Standalone, Standard. It would be clearer and simpler to list them directly in the README at the top level.**

**Comment by lgrateau** [comment]
Thanks Rachel. Put this informations at the top level and refresh it with the 8.10.x references.
