### ISSUE TITLE
Fix JVM out of memory for ODM for Developer container

### ISSUE THREAD

**Issue by devdlscustom** [ODMDev/odm-ondocker#202]
Ref:  https://github.com/ODMDev/odm-ondocker/issues/58

Running ODM for Developer 8.10 container on Mac laptop natively.  While trying to complete a tutorial (lab exercise) from the Knowledge Center, the JVM is constantly running out of memory.  Per instructions (https://github.com/ODMDev/odm-ondocker/blob/master/standalone/dockerhub/full-description.md ) running Docker container with 2 GB memory.  Laptop has 16 GB RAM.  Also tried running Docker container with 4 GB memory but that made the problem worse.  Given the referenced article I now understand why.  The solution to fix this issue isn't straight forward.  How I'd normally fix JVM Max Heap size for WAS/Liberty don't seem feasible.  This ODM for Developer container is completely useless if this JVM out of memory issue can't be resolved.

**Comment by lgrateau** [comment]
@devdlscustom on mac OSX you should configure docker to use more memory. To do that 
Go to Docker -> Preferences -> Advanced -> Memory to 4 GB 
Restart docker and it should solve your issue.
