### ISSUE TITLE
Set MaximumHeapSize value with environment variables

### ISSUE THREAD

**Issue by JoNicolas** [ODMDev/odm-ondocker#208]
Hello Team,

After digging into the actual configuration of the Maximum Heap Size, I need to allocate more memory due to OutOfMemry Heap size error.

After looking into the documentation, I was not able to tweak the `Xmx` option via the following environment variables `JAVA_OPTS` nor `JVM_ARGS`

The only solution I found : use the ` IBM_JAVA_OPTIONS` (which permits me to use th required parameters). 

Is it the right behaviour ?

Nicolas

**Comment by lgrateau** [comment]
Hi Nicolas,

Have you try to increase the memory via the --memory-reservation flag.
docker run -e LICENSE=accept -p 9060:9060 -p 9443:9443  -m 2048M **--memory-reservation 2048M**  -e SAMPLE=true ibmcom/odm:8.10

Regards,

LAurent

**Comment by JoNicolas** [comment]
Hello Laurent,

I am using a Docker compose file (v3) and it seems that this option is only available when using Docker in swarm mode.

So I think I will need to downgradet my docker-compose file to v2.

Nicolas
