### ISSUE TITLE
IBMCOM Volume Command Causing Crash

### ISSUE THREAD

**Issue by varnem2** [ODMDev/odm-ondocker#213]
Hello, I'm running this docker command in an empty directory. It seems as though I'm receiving database not found errors when I mount the database.
[ERROR   ] Could not lookup datasource named 'jdbc/ilogDataSource'
[WARNING ] reaper.stall

docker run -e LICENSE=accept  -m 8000M --memory-reservation 8000M -p 9060:9060 -p 9443:9443 -v ODM810:/config/dbdata/ -e SAMPLE=false  ibmcom/odm:8.10.2

**Comment by mmouly** [comment]
Hello,

It appears that "-v ODM810:/config/dbdata/" doesn't create the volume. It's the reason why datasource is not found. You can have a try using : "-v $PWD/ODM810:/config/dbdata/" or using an absolute PATH.

**Comment by varnem2** [comment]
Thanks for your help on this issue @mmouly. Do you know, is this true with all of docker or just the IBMODM image?

**Comment by mmouly** [comment]
I think it's always true as according to docker documentation : https://docs.docker.com/storage/bind-mounts/
the mount path is always expecting an absolute path.

**Comment by varnem2** [comment]
Thanks mmouly! :)

**Comment by varnem2** [comment]
For documentation purposes, it seems as though using $PWD in the file path doesn't work. Absolute path is the only answer.
