### ISSUE TITLE
script does not work in RHEL8

### ISSUE THREAD

**Issue by alainrobert** [ODMDev/odm-ondocker#258]
https://github.com/ODMDev/odm-ondocker/blob/9ad76ba7009a72dea9caef0b65dc99749f28a5af/decisioncenter/script/setUTF8Locale.sh#L3

set LANG=en_us.UTF-8 does not work with RHEL 8.
We should consider setting LANG=C.UTF-8 without any condition.

**Comment by mmouly** [comment]
done
