### ISSUE TITLE
Links between DC and the RES should be dynamic and not reference localhost

### ISSUE THREAD

**Issue by lgrateau** [ODMDev/odm-ondocker#26]

**Comment by rachel-orti** [comment]
Here is what we currently have as servers declared by default in DC: ![screen shot 2017-08-21 at 17 17 20](https://user-images.githubusercontent.com/29668282/29525972-9e4f5360-8694-11e7-85b4-2b2b5c4f3ef3.png)

**Comment by rachel-orti** [comment]
With the fix for the standard topology, it is also working for the cluster topology.

**Comment by rachel-orti** [comment]
For the standard and cluster topologies, we have the following servers that are declared by default:
- Decision Runner Server: http://decisionrunner:9080/DecisionRunner
- RES Server: http://decisionserverconsole:9080/res
For the standalone topology, we have the following servers that are declared by default:
- Decision Runner Server: http://localhost:9060/DecisionRunner
- RES Server: http://localhost:9060/res
NB:Currently, we still have to add the user names and passwords by hand.
