### ISSUE TITLE
Decision Server Console references updateDSRConfigurations.sh script

### ISSUE THREAD

**Issue by alainrobert** [ODMDev/odm-ondocker#269]
https://github.com/ODMDev/odm-ondocker/blob/6e54884ad67cbc5a2d709c620b45e5c874ac0b89/decisionserver/decisionserverconsole/script/run.sh#L20

In the script folder for Decision ServerConsole there  is shell script   update**DSC**Configurations.sh  
`decisionserver/decisionserverconsole/script/updateDSCConfigurations.sh`

however the run.sh script itself references update**DSR**Configurations.sh  instead.

**Comment by lgrateau** [comment]
Fixed in the vnext-release branch. Will be available on the next release.
