### ISSUE TITLE
Building odm-standalone fails: Step 1/75 : ARG FROMLIBERTY ..  Please provide a source image with `from` prior to commit

### ISSUE THREAD

**Issue by rscher** [ODMDev/odm-ondocker#273]
ODM 8.10.5  installed
[odm-ondocker_build-files.zip](https://github.com/ODMDev/odm-ondocker/files/6669278/odm-ondocker_build-files.zip)

[root@trappers1 odm-ondocker]# cat /etc/os-release
NAME="Red Hat Enterprise Linux Server"
VERSION="7.9 (Maipo)"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.9:GA:server"

[root@trappers1 odm-ondocker]# docker version
Client:
 Version:         1.13.1
 API version:     1.26
 Package version: docker-1.13.1-208.git7d71120.el7_9.x86_64
 Go version:      go1.10.3
 Git commit:      7d71120/1.13.1
 Built:           Fri Jun  4 10:20:12 2021
 OS/Arch:         linux/amd64

Server:
 Version:         1.13.1
 API version:     1.26 (minimum version 1.12)
 Package version: docker-1.13.1-208.git7d71120.el7_9.x86_64
 Go version:      go1.10.3
 Git commit:      7d71120/1.13.1
 Built:           Fri Jun  4 10:20:12 2021
 OS/Arch:         linux/amd64
 Experimental:    false

[root@trappers1 odm-ondocker]# docker-compose  version
docker-compose version 1.18.0, build 8dd22a9
docker-py version: 2.6.1
CPython version: 3.6.8
OpenSSL version: OpenSSL 1.0.2k-fips  26 Jan 2017

[root@trappers1 odm-ondocker]# **docker-compose -f odm-standalone.yml up**
Building odm-standalone
Step 1/75 : ARG FROMLIBERTY
ERROR: Service 'odm-standalone' failed to build: Please provide a source image with `from` prior to commit

VM accessible if needed/can slack root pw
[root@trappers1 odm-ondocker]# hostname
trappers1.fyre.ibm.com
[root@trappers1 odm-ondocker]# hostname -I
10.11.35.121 **9.30.99.209** 192.168.122.1 172.17.0.1 172.18.0.1
[root@trappers1 odm-ondocker]# pwd
/opt/IBM/ODM8105/odm-ondocker

ODM 8.10.5 sample server installed and running
http://9.30.99.209:9090/decisioncenter

-Russ

**Comment by rscher** [comment]
VM accessible if needed/will provide root pw

[root@trappers1 odm-ondocker]# hostname
**trappers1.fyre.ibm.com**
[root@trappers1 odm-ondocker]# hostname -i
10.11.35.121
[root@trappers1 odm-ondocker]# pwd
**/opt/IBM/ODM8105/odm-ondocker**

-Russ

**Comment by rscher** [comment]
sorry,  external  IP:   **9.30.99.209**

[root@trappers1 8.10.0-WS-ODM_DSR-LIN_X86-RP005]# hostname -I
10.11.35.121 **9.30.99.20**9 192.168.122.1 172.17.0.1 172.18.0.1

slack me if root pw is needed
-Russ

**Comment by lgrateau** [comment]
After investigating in your machine, the problem come from the Docker version / Docker-compose.
Your docker version is  1.13.1 and docker-compose is 1.18.0 (4 Years old) which does not support the  version "3" of the docker-compose spec. https://docs.docker.com/compose/compose-file/compose-versioning/
Our docker-compose is in version "3".
My suggestion is to use a RHEL 8 instead of a RHEL 7 machine.

**Comment by rscher** [comment]
> o

Many thanks Laurent ! 
will try RHEL 8.3 or 8.4 with the correct docker and docker-compose versions/

-Russ

**Comment by rscher** [comment]
resolved after installing latest docker and docker-compose versions-

[root@trappers1 ~]# docker version
Client:
 Cloud integration: 1.0.17
 **Version:           20.10.7**

Server: Docker Engine - Community

 Engine:
  Version:          20.10.7

[root@trappers1 ~]# docker-compose version
**docker-compose version 1.29.2**, build 5becea4c
docker-py version: 5.0.0
CPython version: 3.7.10
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019

closing issue, thanks again !
-Russ
