### ISSUE TITLE
Warnings from Solr in the log for DC when starting the DC container

### ISSUE THREAD

**Issue by rachel-orti** [ODMDev/odm-ondocker#34]
When we start the DC container, we get the following warnings. We should check whether it is normal or not to get these warnings. In the best world, it would be better to not have warnings.

decisioncenter_1         | [WARNING ] CWWKG0033W: The value [decisioncenter-libraries] specified for the reference attribute [commonLibraryRef] was not found in the configuration.
decisioncenter_1         | [WARNING ] CWWKG0033W: The value [decisioncenter-libraries] specified for the reference attribute [commonLibraryRef] was not found in the configuration.

decisioncenter_1         | [WARNING ] Couldn't add files from /tmp/solr_config7046266713554902815.dir/lib to classpath: /tmp/solr_config7046266713554902815.dir/lib
decisioncenter_1         | [WARNING ] [dc] Solr index directory '/tmp/decisioncenter-solr-dir/dc/index' doesn't exist. Creating new index...
decisioncenter_1         | [WARNING ] Cannot write to config directory /tmp/solr_config7046266713554902815.dir/configsets/shared/conf; switching to use InMemory storage instead.
decisioncenter_1         | [WARNING ] Starting optimize... Reading and rewriting the entire index! Use with care.

**Comment by rachel-orti** [comment]
The warnings related to decisioncenter-libraries have been fixed with the previous commit.

**Comment by mmouly** [comment]
The optimize call in solr is not a "real" optimize.
See  https://issues.apache.org/jira/browse/SOLR-3141
I just discuss it with Cyril Mathey and he agree to remove it in bdsl-core-search 

SolrService line 160

	@Override
	public final void endIndexUpdate() throws OperationFailedException {
		checkTransaction();

		try {
			getSolrClient().commit();
			getSolrClient().optimize();
			_txLock.unlock();
		} catch (Exception e) {
			throw new OperationFailedException(e);
		}
	}

**Comment by mmouly** [comment]
VTT tests doesn't show the following warning on liberty tests by removing optimize() call 
[WARNING ] Starting optimize... Reading and rewriting the entire index! Use with care.

before
http://odmvttui04u.fr.eurolabs.ibm.com/rest/files/5a0d26b0669b900cab472390

after
http://odmvttui04u.fr.eurolabs.ibm.com/rest/files/5a0e7add669b900caba42ccf

Tests are ok
http://odm-services.francelab.fr.ibm.com/vtt/c/results/view?campaignId=1510886720775&requestId=5a0e7531f004b82879f78c01&testSuiteId=5a0e7ada669b900caba40f18&testSuiteName=com.ibm.rules.decisioncenter.web.functionaltests.tests.features.search.SearchTest&success&failures&errors

Concerning other warnings 
[WARNING ] Couldn't add files from C:\Users\rulesadm\AppData\Local\Temp\solr_config4192384070092565137.dir\lib to classpath: C:\Users\rulesadm\AppData\Local\Temp\solr_config4192384070092565137.dir\lib
[WARNING ] [dc] Solr index directory 'C:\Users\rulesadm\AppData\Local\Temp\decisioncenter-solr-dir\dc\index' doesn't exist. Creating new index...
[WARNING ] Cannot write to config directory C:\Users\rulesadm\AppData\Local\Temp\solr_config4192384070092565137.dir\configsets\shared\conf; switching to use InMemory storage instead.
[ERROR   ] null
ilog.rules.teamserver.model.IlrConnectException

I still investigating. It looks like new Solr version deployed June 30 need some new variable environment
