### ISSUE TITLE
Find a way to configure the amount of RAM 

### ISSUE THREAD

**Issue by lgrateau** [ODMDev/odm-ondocker#58]

**Comment by lgrateau** [comment]
https://dzone.com/articles/java-inside-docker-what-you-must-know-to-not-fail

**Comment by yiquanzhou** [comment]
We can configure the memory usage at different levels:

- Docker virtual machine: the physical machine memory or specified by ```docker-machine create -d virtualbox  –virtualbox-memory ‘1024’ docker1024```
- Docker container: `docker run ... -m 150M ...` option, this gives 150M in RAM and 150M in SWAP
- JVM/application: default JVM heap size is 1/4 of the physical memory (docker virtual machine here), can be configured with `-Xmx` JAVA_OPTION

If we don’t specify explicitly the max JVM heap that app is allowed to use by -Xmx option, the application could try to allocate more memory than the max memory of the container.

**Comment by yiquanzhou** [comment]
In Liberty, memory options can be set in jvm.options file. 
More details here: http://www-01.ibm.com/support/docview.wss?uid=swg21596474

In Liberty Docker image, setting these options by passing environment variables is not yet supported: https://github.com/WASdev/ci.docker/issues/112

**Comment by yiquanzhou** [comment]
`JVM_ARGS` can be used to pass jvm arguments to liberty profile.

For example: `docker run -e JVM_ARGS='-Xmx100m' websphere-liberty`

**Comment by yiquanzhou** [comment]
The memory unit used in Kubernetes could be "Mi" or "M" but in the java options only "M" is allowed, otherwise the option is ignored.
