### ISSUE TITLE
Intermittent NullPointerException when launching DC with a sample database

### ISSUE THREAD

**Issue by rachel-orti** [ODMDev/odm-ondocker#88]
This error occurs notably intermittently with the standard topology using a sample database with postgreSQL:

odm-decisioncenter_1         | [WARNING ] Couldn't add files from /tmp/solr_config5718955126111243725.dir/lib to classpath: /tmp/solr_config5718955126111243725.dir/lib
odm-decisioncenter_1         | [WARNING ] [dc] Solr index directory '/tmp/decisioncenter-solr-dir/dc/index' doesn't exist. Creating new index...
odm-decisioncenter_1         | [WARNING ] Cannot write to config directory /tmp/solr_config5718955126111243725.dir/configsets/shared/conf; switching to use InMemory storage instead.
odm-decisioncenter_1         | [WARNING ] Starting optimize... Reading and rewriting the entire index! Use with care.
odm-decisioncenter_1         | [ERROR   ] java.lang.NullPointerException
odm-decisioncenter_1         | 	at org.apache.lucene.index.FreqProxTermsWriter.applyDeletes(FreqProxTermsWriter.java:60)
odm-decisioncenter_1         | 	at org.apache.lucene.index.FreqProxTermsWriter.flush(FreqProxTermsWriter.java:102)
odm-decisioncenter_1         | 	at org.apache.lucene.index.DefaultIndexingChain.flush(DefaultIndexingChain.java:126)
odm-decisioncenter_1         | 	at org.apache.lucene.index.DocumentsWriterPerThread.flush(DocumentsWriterPerThread.java:422)
odm-decisioncenter_1         | 	at org.apache.lucene.index.DocumentsWriter.doFlush(DocumentsWriter.java:503)
odm-decisioncenter_1         | 	at org.apache.lucene.index.DocumentsWriter.flushAllThreads(DocumentsWriter.java:615)
odm-decisioncenter_1         | 	at org.apache.lucene.index.IndexWriter.prepareCommitInternal(IndexWriter.java:2804)
odm-decisioncenter_1         | 	at org.apache.lucene.index.IndexWriter.commitInternal(IndexWriter.java:2970)
odm-decisioncenter_1         | 	at org.apache.lucene.index.IndexWriter.commit(IndexWriter.java:2935)
odm-decisioncenter_1         | 	at org.apache.solr.update.DirectUpdateHandler2.commit(DirectUpdateHandler2.java:619)
odm-decisioncenter_1         | 	at org.apache.solr.update.processor.RunUpdateProcessor.processCommit(RunUpdateProcessorFactory.java:94)
odm-decisioncenter_1         | 	at org.apache.solr.update.processor.UpdateRequestProcessor.processCommit(UpdateRequestProcessor.java:61)
odm-decisioncenter_1         | 	at org.apache.solr.update.processor.DistributedUpdateProcessor.doLocalCommit(DistributedUpdateProcessor.java:1628)
odm-decisioncenter_1         | 	at org.apache.solr.update.processor.DistributedUpdateProcessor.processCommit(DistributedUpdateProcessor.java:1605)
odm-decisioncenter_1         | 	at org.apache.solr.update.processor.LogUpdateProcessorFactory$LogUpdateProcessor.processCommit(LogUpdateProcessorFactory.java:160)
odm-decisioncenter_1         | 	at org.apache.solr.handler.RequestHandlerUtils.handleCommit(RequestHandlerUtils.java:68)
odm-decisioncenter_1         | 	at org.apache.solr.handler.ContentStreamHandlerBase.handleRequestBody(ContentStreamHandlerBase.java:63)
odm-decisioncenter_1         | 	at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:155)
odm-decisioncenter_1         | 	at org.apache.solr.core.SolrCore.execute(SolrCore.java:2102)
odm-decisioncenter_1         | 	at org.apache.solr.client.solrj.embedded.EmbeddedSolrServer.request(EmbeddedSolrServer.java:178)
odm-decisioncenter_1         | 	at org.apache.solr.client.solrj.SolrRequest.process(SolrRequest.java:149)
odm-decisioncenter_1         | 	at org.apache.solr.client.solrj.SolrClient.commit(SolrClient.java:482)
odm-decisioncenter_1         | 	at org.apache.solr.client.solrj.SolrClient.commit(SolrClient.java:463)
odm-decisioncenter_1         | 	at com.ibm.rules.bdsl.search.solr.SolrService.endIndexUpdate(SolrService.java:159)
odm-decisioncenter_1         | 	at com.ibm.rules.decisioncenter.web.search.SearchService.endIndexUpdate(SearchService.java:147)
odm-decisioncenter_1         | 	at com.ibm.rules.bdsl.search.IndexTransaction.commit(IndexTransaction.java:107)
odm-decisioncenter_1         | 	at com.ibm.rules.bdsl.search.IndexTransaction.onSuccess(IndexTransaction.java:89)
odm-decisioncenter_1         | 	at com.ibm.rules.bdsl.search.IndexTransaction.updateIndex(IndexTransaction.java:63)
odm-decisioncenter_1         | 	at com.ibm.rules.decisioncenter.web.search.SearchIndexBuilder.updateBranchCore(SearchIndexBuilder.java:251)
odm-decisioncenter_1         | 	at com.ibm.rules.decisioncenter.web.search.SearchIndexBuilder.updateBranch(SearchIndexBuilder.java:162)
odm-decisioncenter_1         | 	at com.ibm.rules.decisioncenter.web.search.SearchIndexBuilder.updateAll(SearchIndexBuilder.java:139)
odm-decisioncenter_1         | 	at com.ibm.rules.decisioncenter.web.search.IndexerService$DatasourceUpdater.doRun(IndexerService.java:207)
odm-decisioncenter_1         | 	at com.ibm.rules.decisioncenter.web.search.IndexerServiceThread$AbstractPeriodicUpdater.run(IndexerServiceThread.java:244)
odm-decisioncenter_1         | 	at com.ibm.rules.decisioncenter.web.search.IndexerServiceThread$Service.run(IndexerServiceThread.java:87)
odm-decisioncenter_1         | 	at com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(AbstractExecutionThreadService.java:66)
odm-decisioncenter_1         | 	at com.google.common.util.concurrent.Callables$4.run(Callables.java:122)
odm-decisioncenter_1         | 	at java.lang.Thread.run(Thread.java:795)
odm-decisioncenter_1         |
odm-decisioncenter_1         | [ERROR   ] Embeded solr service is asked to recover. Operation not supported
odm-decisioncenter_1         | [WARNING ] Failed to update 'brm.Branch:4:4 (%current_key)' index to revision '40'. Transaction failed
odm-decisioncenter_1         | [ERROR   ] org.apache.solr.common.SolrException: Exception writing document id brm.Branch:7:7/f1f9ec9a-78b9-444a-a01c-105e948015c0/en_US to the index; possible analysis error.
odm-decisioncenter_1         | 	at org.apache.solr.update.DirectUpdateHandler2.addDoc(DirectUpdateHandler2.java:180)
odm-decisioncenter_1         | 	at org.apache.solr.update.processor.RunUpdateProcessor.processAdd(RunUpdateProcessorFactory.java:68)
odm-decisioncenter_1         | 	at org.apache.solr.update.processor.UpdateRequestProcessor.processAdd(UpdateRequestProcessor.java:48)
odm-decisioncenter_1         | 	at org.apache.solr.update.processor.DistributedUpdateProcessor.versionAdd(DistributedUpdateProcessor.java:960)
odm-decisioncenter_1         | 	at org.apache.solr.update.processor.DistributedUpdateProcessor.processAdd(DistributedUpdateProcessor.java:712)
odm-decisioncenter_1         | 	at org.apache.solr.update.processor.LogUpdateProcessorFactory$LogUpdateProcessor.processAdd(LogUpdateProcessorFactory.java:103)
odm-decisioncenter_1         | 	at org.apache.solr.handler.loader.XMLLoader.processUpdate(XMLLoader.java:250)
odm-decisioncenter_1         | 	at org.apache.solr.handler.loader.XMLLoader.load(XMLLoader.java:177)
odm-decisioncenter_1         | 	at org.apache.solr.handler.UpdateRequestHandler$1.load(UpdateRequestHandler.java:94)
odm-decisioncenter_1         | 	at org.apache.solr.handler.ContentStreamHandlerBase.handleRequestBody(ContentStreamHandlerBase.java:69)
odm-decisioncenter_1         | 	at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:155)
odm-decisioncenter_1         | 	at org.apache.solr.core.SolrCore.execute(SolrCore.java:2102)
odm-decisioncenter_1         | 	at org.apache.solr.client.solrj.embedded.EmbeddedSolrServer.request(EmbeddedSolrServer.java:178)
odm-decisioncenter_1         | 	at org.apache.solr.client.solrj.SolrRequest.process(SolrRequest.java:149)
odm-decisioncenter_1         | 	at org.apache.solr.client.solrj.SolrClient.add(SolrClient.java:106)
odm-decisioncenter_1         | 	at org.apache.solr.client.solrj.SolrClient.add(SolrClient.java:71)
odm-decisioncenter_1         | 	at org.apache.solr.client.solrj.SolrClient.add(SolrClient.java:85)
odm-decisioncenter_1         | 	at com.ibm.rules.bdsl.search.solr.SolrService.indexArtifacts(SolrService.java:988)
odm-decisioncenter_1         | 	at com.ibm.rules.decisioncenter.web.search.SearchService.indexArtifacts(SearchService.java:152)
odm-decisioncenter_1         | 	at com.ibm.rules.decisioncenter.web.search.SearchIndexBuilder$6.transaction(SearchIndexBuilder.java:244)
odm-decisioncenter_1         | 	at com.ibm.rules.decisioncenter.web.search.SearchIndexBuilder$6.transaction(SearchIndexBuilder.java:240)
odm-decisioncenter_1         | 	at com.ibm.rules.bdsl.search.IndexTransaction.updateIndex(IndexTransaction.java:51)
odm-decisioncenter_1         | 	at com.ibm.rules.decisioncenter.web.search.SearchIndexBuilder.updateBranchCore(SearchIndexBuilder.java:251)
odm-decisioncenter_1         | 	at com.ibm.rules.decisioncenter.web.search.SearchIndexBuilder.updateBranch(SearchIndexBuilder.java:162)
odm-decisioncenter_1         | 	at com.ibm.rules.decisioncenter.web.search.SearchIndexBuilder.updateAll(SearchIndexBuilder.java:139)
odm-decisioncenter_1         | 	at com.ibm.rules.decisioncenter.web.search.IndexerService$DatasourceUpdater.doRun(IndexerService.java:207)
odm-decisioncenter_1         | 	at com.ibm.rules.decisioncenter.web.search.IndexerServiceThread$AbstractPeriodicUpdater.run(IndexerServiceThread.java:244)
odm-decisioncenter_1         | 	at com.ibm.rules.decisioncenter.web.search.IndexerServiceThread$Service.run(IndexerServiceThread.java:87)
odm-decisioncenter_1         | 	at com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(AbstractExecutionThreadService.java:66)
odm-decisioncenter_1         | 	at com.google.common.util.concurrent.Callables$4.run(Callables.java:122)
odm-decisioncenter_1         | 	at java.lang.Thread.run(Thread.java:795)
odm-decisioncenter_1         | Caused by: org.apache.lucene.store.AlreadyClosedException: this IndexWriter is closed
odm-decisioncenter_1         | 	at org.apache.lucene.index.IndexWriter.ensureOpen(IndexWriter.java:720)
odm-decisioncenter_1         | 	at org.apache.lucene.index.IndexWriter.ensureOpen(IndexWriter.java:734)
odm-decisioncenter_1         | 	at org.apache.lucene.index.IndexWriter.updateDocument(IndexWriter.java:1473)
odm-decisioncenter_1         | 	at org.apache.solr.update.DirectUpdateHandler2.doNormalUpdate(DirectUpdateHandler2.java:282)
odm-decisioncenter_1         | 	at org.apache.solr.update.DirectUpdateHandler2.addDoc0(DirectUpdateHandler2.java:214)
odm-decisioncenter_1         | 	at org.apache.solr.update.DirectUpdateHandler2.addDoc(DirectUpdateHandler2.java:169)
odm-decisioncenter_1         | 	... 30 more
odm-decisioncenter_1         | Caused by: java.lang.NullPointerException
odm-decisioncenter_1         | 	at org.apache.lucene.index.FreqProxTermsWriter.applyDeletes(FreqProxTermsWriter.java:60)
odm-decisioncenter_1         | 	at org.apache.lucene.index.FreqProxTermsWriter.flush(FreqProxTermsWriter.java:102)
odm-decisioncenter_1         | 	at org.apache.lucene.index.DefaultIndexingChain.flush(DefaultIndexingChain.java:126)
odm-decisioncenter_1         | 	at org.apache.lucene.index.DocumentsWriterPerThread.flush(DocumentsWriterPerThread.java:422)
odm-decisioncenter_1         | 	at org.apache.lucene.index.DocumentsWriter.doFlush(DocumentsWriter.java:503)
odm-decisioncenter_1         | 	at org.apache.lucene.index.DocumentsWriter.flushAllThreads(DocumentsWriter.java:615)
odm-decisioncenter_1         | 	at org.apache.lucene.index.IndexWriter.prepareCommitInternal(IndexWriter.java:2804)
odm-decisioncenter_1         | 	at org.apache.lucene.index.IndexWriter.commitInternal(IndexWriter.java:2970)
odm-decisioncenter_1         | 	at org.apache.lucene.index.IndexWriter.commit(IndexWriter.java:2935)
odm-decisioncenter_1         | 	at org.apache.solr.update.DirectUpdateHandler2.commit(DirectUpdateHandler2.java:619)
odm-decisioncenter_1         | 	at org.apache.solr.update.processor.RunUpdateProcessor.processCommit(RunUpdateProcessorFactory.java:94)
odm-decisioncenter_1         | 	at org.apache.solr.update.processor.UpdateRequestProcessor.processCommit(UpdateRequestProcessor.java:61)
odm-decisioncenter_1         | 	at org.apache.solr.update.processor.DistributedUpdateProcessor.doLocalCommit(DistributedUpdateProcessor.java:1628)
odm-decisioncenter_1         | 	at org.apache.solr.update.processor.DistributedUpdateProcessor.processCommit(DistributedUpdateProcessor.java:1605)
odm-decisioncenter_1         | 	at org.apache.solr.update.processor.LogUpdateProcessorFactory$LogUpdateProcessor.processCommit(LogUpdateProcessorFactory.java:160)
odm-decisioncenter_1         | 	at org.apache.solr.handler.RequestHandlerUtils.handleCommit(RequestHandlerUtils.java:68)
odm-decisioncenter_1         | 	at org.apache.solr.handler.ContentStreamHandlerBase.handleRequestBody(ContentStreamHandlerBase.java:63)
odm-decisioncenter_1         | 	at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:155)
odm-decisioncenter_1         | 	at org.apache.solr.core.SolrCore.execute(SolrCore.java:2102)
odm-decisioncenter_1         | 	at org.apache.solr.client.solrj.embedded.EmbeddedSolrServer.request(EmbeddedSolrServer.java:178)
odm-decisioncenter_1         | 	at org.apache.solr.client.solrj.SolrRequest.process(SolrRequest.java:149)
odm-decisioncenter_1         | 	at org.apache.solr.client.solrj.SolrClient.commit(SolrClient.java:482)
odm-decisioncenter_1         | 	at org.apache.solr.client.solrj.SolrClient.commit(SolrClient.java:463)
odm-decisioncenter_1         | 	at com.ibm.rules.bdsl.search.solr.SolrService.endIndexUpdate(SolrService.java:159)
odm-decisioncenter_1         | 	at com.ibm.rules.decisioncenter.web.search.SearchService.endIndexUpdate(SearchService.java:147)
odm-decisioncenter_1         | 	at com.ibm.rules.bdsl.search.IndexTransaction.commit(IndexTransaction.java:107)
odm-decisioncenter_1         | 	at com.ibm.rules.bdsl.search.IndexTransaction.onSuccess(IndexTransaction.java:89)
odm-decisioncenter_1         | 	at com.ibm.rules.bdsl.search.IndexTransaction.updateIndex(IndexTransaction.java:63)
odm-decisioncenter_1         | 	... 9 more
odm-decisioncenter_1         |
odm-decisioncenter_1         | [WARNING ] Failed to update 'brm.Branch:7:7 (%current_key)' index to revision '62'. Transaction failed
odm-decisioncenter_1         | [WARNING ] Starting optimize... Reading and rewriting the entire index! Use with care.

**Comment by mmouly** [comment]
I reproduce the exception on local dev env but not on VTT VM. Try to figure out what can be the difference.

**Comment by ameralmousa** [comment]
Any update on how you resolved this issue? I am running into similar intermittent, when indexing newly created collection.

**Comment by mmouly** [comment]
Hello, the issue was an ODM Decision Center defect and the correction will be provided with the next fix pack. If you need an urgent correction, don't hesitate to contact the support team
